<?php

return [
    'ABIDJAN' => [
        'II PLATEAUX',
        'MARCORY',
        'CITE SIR',
        'YOPOUGON',
        'COCODY',
        'PLATEAU',
        'BINGERVILLE',
        'TREICHVILLE',
        'FAYA',
        'KOUMASSI',
        'ATTECOUBE',
        'ABOBO',
        'ADJAME',
        'PORT-BOUET',
        'FEHKESSE',
    ],

    // Villes principales de Côte d'Ivoire
    'ABENGOUROU' => [],
    'ADZOPÉ' => [],
    'AGBOVILLE' => [],
    'AGNIBILÉKRO' => [],
    'AKOUPÉ' => [],
    'ANYAMA' => [],
    'BINGERVILLE' => [],
    'BONDOUKOU' => [],
    'BOUAFLÉ' => [],
    'BOUAKÉ' => [],
    'BOUNA' => [],
    'BOUNDIALI' => [],
    'BONOUA' => [],
    'DABOU' => [],
    'DALOA' => [],
    'DANANÉ' => [],
    'DAOUKRO' => [],
    'DIMBOKRO' => [],
    'DIVO' => [],
    'DUÉKOUÉ' => [],
    'FERKESSEDOUGOU' => [],
    'GAGNOA' => [],
    'GRAND-BASSAM' => [],
    'GUIGLO' => [],
    'ISSIA' => [],
    'KATIOLA' => [],
    'KORHOGO' => [],
    'LAKOTA' => [],
    'MAN' => [],
    'ODIENNÉ' => [],
    'OUMÉ' => [],
    'SAN-PÉDRO' => [],
    'SÉGUÉLA' => [],
    'SINFRA' => [],
    'SONGON' => [],
    'SOUBRÉ' => [],
    'TANDA' => [],
    'TIASSALÉ' => [],
    'TIEBISSOU' => [],
    'TINGRÉLA' => [],
    'TOUMODI' => [],
    'VAVOUA' => [],
    'YAMOUSSOUKRO' => [],
    'ZUÉNOULA' => [],
];
